jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-distutils
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python main_webcam.py
